src/BabyStore/BabyStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BabyStore.Domain.Abstract;
using BabyStore.Domain.Entities;
using BabyStore.WebUI.Models;

namespace BabyStore.WebUI.Controllers
{
    public class CartController : Controller
    {

        private IProductRepository _repository;
        private IOrderProcessor _orderProcessor;
        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            _repository = repo;
            _orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                _orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

    }
}

src/BabyStore/BabyStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BabyStore.Domain.Abstract;

namespace BabyStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository _repository;
        public NavController(IProductRepository repo)
        {
            _repository = repo;
        }
        public PartialViewResult Menu(string category=null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

src/BabyStore/BabyStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BabyStore.Domain.Abstract;
using BabyStore.Domain.Entities;
using BabyStore.WebUI.Models;


namespace BabyStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _repository;
        public int PageSize = 4;
        public ProductController(IProductRepository productRepository)
        {
            this._repository = productRepository;
        }
        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = _repository.Products
                .Where(p=>category==null||p.Category==category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category==null?
                    _repository.Products.Count():
                    _repository.Products.Where(e=>e.Category==category).Count()
                },
                CurrentCategory=category
            };

            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = _repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

src/BabyStore/BabyStore.WebUI/Views/Shared/ProductSummary.cshtml
@model BabyStore.Domain.Entities.Product


<div class="col-md-3">
    <div class="card mb-3 box-shadow">

        @if (Model.ImageData != null)
        {
            <img class="card-img-top" src="@Url.Action("GetImage", "Product", new {Model.ProductID})" alt="Card image cap" />
        }
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>

            <!--<p class="card-text">@Model.Description</p>-->
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <div class="item">
                        @using (Html.BeginForm("AddToCart", "Cart"))
                        {
                            @Html.HiddenFor(x => x.ProductID)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <button type="submit" class="btn btn-sm btn-outline-secondary">Добавить в корзину</button>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <small class="text-muted">@Model.Price.ToString("c")</small>
        </div>
    </div>
</div>

src/BabyStore/BabyStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <<link href="@Url.Content("~/Content/")Admin.css" rel="stylesheet" type="text/css">
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

src/BabyStore/BabyStore.WebUI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Navbar Template for Bootstrap</title>

    <link href="@Url.Content("~/Content/")bootstrap.min.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")navbar.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")starter-template.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/")sticky-footer-navbar.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Детский магазин</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @{Html.RenderAction("Menu", "Nav", new { @class = "nav-link" });}
                </li>
            </ul>
        </div>
        <div class="navbar-nav px-3">
            <div class="alert alert-light" role="alert">
                <div id="header">
                    @{Html.RenderAction("Summary", "Cart");}
                </div>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">&copy; @DateTime.Now.Year – приложение ASP.NET</span>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write @Scripts.Render("~/Scripts/jquery-slim.min.js")</script>
    @Scripts.Render("~/Scripts/popper.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")

</body>
</html>